### ISSUE TITLE
Split classes into their own files

### ISSUE THREAD

**Issue by cookejames** [randuhmm/rad-esp8266#3]
This would be easier to maintain, extend and submit PRs (less chance of conflicts/easier to see what is being updated)

**Comment by randuhmm** [comment]
Excellent idea! I am gonna hafta read up on how to best accomplish this, the last I tried to split up the files, I got a ton of errors from the IDE :(

**Comment by cookejames** [comment]
It should be pretty simple - here is a [similar class I created](https://github.com/cookejames/SarahHomeESP8266/tree/master/src) for doing basic boilerplate for my MQTT network. If you are still using the Arduino IDE I would recommend [PlatformIO](http://platformio.org/) as it is much better. I'd be quite happy to submit a PR when I get the time (maybe this weekend?) as it seems like we have similar aims.

**Comment by cookejames** [comment]
You could also do worse than looking through some of the source of ST_Anything - @ogiewon looks to be far more experienced than I am in C

**Comment by randuhmm** [comment]
> I would recommend PlatformIO as it is much better

Thanks, I will check it out!

I am also quite rusty in C/C++ these days. I have spent much more time with Python and JavaScript of late and have gotten used to the quicker development cycles and easier debugging.

**Comment by cookejames** [comment]
Tell me about it node/JS is my day job.

**Comment by randuhmm** [comment]
> I'd be quite happy to submit a PR when I get the time (maybe this weekend?) as it seems like we have similar aims.

Let me know if you are planning on taking on this task. I will likely be spending some time later this afternoon working on various things.

**Comment by cookejames** [comment]
I had a quick look into this earlier and quickly hit some stumbling blocks as RadFeature and RadSchedule both reference each other and then I ran out of time to carry on.
